### ISSUE TITLE
Implement extension message type

### ISSUE THREAD

**Issue by sschaef** [msgpack4z/msgpack4z-core#2]
There is no implementation here: https://github.com/msgpack4z/msgpack4z-core/blob/fca977fa3b97987c58b77109072c38d2e12f17b5/src/main/scala/msgpack4z/MsgpackUnion.scala#L246

This means that extension types can't be used.

**Comment by xuwei-k** [comment]
https://github.com/msgpack4z/msgpack4z-core/commit/2f3c5bb8b2a58d2ec94e7d7985b439eb247 implemented extension type. released 0.2.0
https://github.com/msgpack4z/msgpack4z-core/tree/v0.2.0

ref https://github.com/msgpack4z/msgpack4z-api/pull/2 https://github.com/msgpack4z/msgpack4z-java07/pull/1
