### ISSUE TITLE
Where's MsgOutBuffer?

### ISSUE THREAD

**Issue by thescalaguy** [msgpack4z/msgpack4z-core#4]
I was trying to follow the examples and couldn't find `MsgOutBuffer`. Have I missed something?  I've added the following in my `build.sbt`

```
libraryDependencies += "com.github.xuwei-k" %% "msgpack4z-core" % "0.3.7" 
```

**Comment by xuwei-k** [comment]
please add following line

```
libraryDependencies += "com.github.xuwei-k" %% "msgpack4z-native" % "0.3.3"
```

https://github.com/msgpack4z/msgpack4z-native/blob/v0.3.3/src/main/scala/msgpack4z/MsgOutBuffer.scala
